services:
  jenkins:
    build: .
    container_name: jenkins
    user: root  # Running as root inside container or setting group permission fixes socket access
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - jenkins_home:/var/jenkins_home
      - /run/user/$(id -u)/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: